apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-v2-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: portfolio-v2
  template:
    metadata:
      labels:
        app: portfolio-v2
    spec:
      containers:
        - name: portfolio-v2
          image: yash5090/portfolio-v2:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
